"""empty message

Revision ID: 2494dc6f985b
Revises: 6172fe806c1d
Create Date: 2023-06-01 11:07:43.610281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2494dc6f985b'
down_revision = '6172fe806c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_userName_key', type_='unique')
        batch_op.drop_column('userName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userName', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_userName_key', ['userName'])

    # ### end Alembic commands ###
