"""empty message

Revision ID: 5614992aaaca
Revises: 5c23cd4514e9
Create Date: 2023-05-23 11:48:43.308452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5614992aaaca'
down_revision = '5c23cd4514e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Coments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('idFilm', sa.String(length=100), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idUsuario'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idFilm'),
    sa.UniqueConstraint('text')
    )
    op.create_table('listCompletadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idFilm', sa.String(length=100), nullable=False),
    sa.Column('nameFilm', sa.String(length=200), nullable=False),
    sa.Column('urlApi', sa.String(length=200), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idUsuario'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idFilm'),
    sa.UniqueConstraint('nameFilm'),
    sa.UniqueConstraint('urlApi')
    )
    op.create_table('listSee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idFilm', sa.String(length=100), nullable=False),
    sa.Column('nameFilm', sa.String(length=200), nullable=False),
    sa.Column('urlApi', sa.String(length=200), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idUsuario'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idFilm'),
    sa.UniqueConstraint('nameFilm'),
    sa.UniqueConstraint('urlApi')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listSee')
    op.drop_table('listCompletadas')
    op.drop_table('Coments')
    # ### end Alembic commands ###
